### ISSUE TITLE
Kategorien für Tools

### ISSUE THREAD

**Issue by sopheck** [FuReSH/tool-storage-metadata#1]
Welche Kategorien wollen wir für Tools anlegen und vorgeben?

Bisher:
categories:    # please select one or more of the following categories by deleting irrelevant lines
  - Q95001953  # research software
  - Q2085518   # format
  - Q9143      # programming language
  - Q151885    # concept
  - Q1438073   # research method
  - Q47146     # user interface
  - Q188860    # software library

Wollen wir die als endgültig übernehmen? (Ist so bereits im Schema hinterlegt.)

**Comment by tillgrallert** [comment]
- Methoden bzw. **Verfahren** sind durch **Theorien** informiert und haben einen *Zweck*. 
- **Verfahren** werden in (mehreren Schichten von) **Software** implementiert, die je eigene Anforderungen an **Hardware** stellt, und mit **Formaten** interagiert (lesen, schreiben).
- **Software** ist in **Sprachen** geschrieben und benötigt im fall von CLIs **Sprachen** zur Interaktion.
- Bei **Formaten** unterscheiden wir nicht zwischen Dateiformaten und Datenserialisierungen.

**Comment by tillgrallert** [comment]
Hier das ganz mal als ein Mermaid flowchart

```mermaid
---
title: categories
---

flowchart LR
    %% nodes
    software[Software]
    hardware[Hardware]
    method(Methods)
    theory(Theories)
    format[Formats]
    language[Languages]
    concept(Concepts)

    %% edges: note that the layout does not imply hierarchies
    theory -->|informs| method
    method -->|is implemented\nby| software
    method & format & language -->|uses| concept
    software -->|requires| hardware
    software -->|is written in| language
    software -->|interaction requires| language
    software -->|reads| format
    software -->|writes| format

    %% classes
    classDef software fill:#ECA7F9
    classDef language fill:#F24726
    classDef concept fill:#F9C710
    classDef format fill:#8BCA4B
    class software software
    class concept concept
    class format format
    class language language
```

Und ein Beispiel, dass die gleichen Farben verwendet

```mermaid
---
title: "categories: example"
---

flowchart LR
    %% nodes
    hardware[Hardware]
    method(Transformation)
    theory(Theories)
    html[HTML]
    xslt[XSLT]
    xslt1[Stylesheet]
    xml[XML]
    concept1(well-formed)
    license(License)
    saxon[Saxon\nXSLT\nProcessor]
    java[Java]
    csv[CSV]

    %% edges
    theory -->|informs| method
    method -->|is implemented\nby| xslt1
    saxon -->|runs| xslt1
    xslt1 -->|reads| html
    xslt1 -->|writes| csv
    xslt1 -->|written in| xslt
    xslt -->|written in| xml
    xml -->|needs to be| concept1
    saxon -->|requires| java
    java -->|requires| hardware
    saxon & java --> |carries| license

%% classes
    classDef software fill:#ECA7F9
    classDef language fill:#F24726
    classDef concept fill:#F9C710
    classDef format fill:#8BCA4B
    class software,saxon,xslt1,java software
    class concept1,license concept
    class html,csv,xml format
    class xslt language
```

**Comment by tillgrallert** [comment]
Wenn ich dieses Struktur mit Wikidata items benennen möchte, dann schlage ich folgende vor:

- Theorie     
    + Q17737
        * theory
        * Theorie             
- Verfahren
    + Q1799072
        * method
        * Verfahren           
    + Q1438073
        * research method
        * Forschungsmethode   
- Software
    + Q7397
        * software
        * Software
    + Q95001953
        * research software                          
- Hardware
    + Q3966
        * computer hardware
        * Hardware
- Sprache
    + Q9143
        * programming language
        * Programmiersprache  
- Format
    + Q2085518
        * format
        * Formatierung        
- Konzept
    + Q151885
        * concept
        * Begriff

**Comment by tillgrallert** [comment]
Sorry, dass ich dieses Issue wieder öffne, aber ich bin bei der Durchsicht der Änderungen im Schema auf zwei Punkte gestoßen, die noch geändert werden müssen (habe ich dort kommentiert). Konkret geht es darum, dass wir uns für je eines der Wikidata Items für *Verfahren* und *Software* entscheiden sollten, anstatt beide von mir recherchierten Möglichkeiten zur Auswahl zuzulassen.

**Comment by sopheck** [comment]
Kein Problem, ich habe bei den Kommentaren geantwortet. Wenn du dein "ok" gibst, pushe ich die Änderungen und schließe das Issue.

**Comment by tillgrallert** [comment]
Super. Vielen Dank!
